"""Explicit local test clock driver. Never imported by Engine or Workflow.

Test synchronization uses an event/request/result ID, never a global pending=0
gate. Hospital events are still generated by the separate causal scheduler.
"""
import asyncio
import copy
from datetime import timedelta
from pathlib import Path

from chain_demo.config import _read_yaml
from chain_demo.validation import canonical_hash, fields, positive, text, timestamp


def load_driver(path,*,test_mode=False):
    if test_mode is not True:raise ValueError("Synthetic driver requires explicit test mode")
    plan=_read_yaml(Path(path))
    fields(plan,{"driver_schema","synthetic","ticks","responses","notes"},where="Local test driver")
    if plan["driver_schema"]!="chain-local-test/v0.3" or plan["synthetic"] is not True:
        raise ValueError("Unsupported synthetic test driver")
    if not isinstance(plan["ticks"],list) or not plan["ticks"]:raise ValueError("Driver ticks required")
    for tick in plan["ticks"]:
        fields(tick,{"anchor","offset_s","wait"},where="Test tick")
        text(tick["anchor"])
        if type(tick["offset_s"]) not in (int,float) or not 0<=tick["offset_s"]<31536000:raise ValueError("Invalid test offset")
        if not isinstance(tick["wait"],dict) or len(tick["wait"])!=1:raise ValueError("One explicit test wait required")
        kind,value=next(iter(tick["wait"].items()))
        if kind in {"source_applied","anchor","result_accepted"}:text(value)
        elif kind in {"hitl_open","hitl_decided","console_bound"}:
            fields(value,{"checkpoint","count"},where="HITL test wait");text(value["checkpoint"]);positive(value["count"],integer=True)
        else:raise ValueError("Unsupported test wait: "+kind)
    if not isinstance(plan["responses"],list):raise ValueError("Response timings must be a list")
    for timing in plan["responses"]:
        fields(timing,{"checkpoint","anchor","offset_s"},where="Synthetic response timing")
        text(timing["checkpoint"]);text(timing["anchor"])
        if type(timing["offset_s"]) not in (int,float) or not 0<=timing["offset_s"]<31536000:raise ValueError("Invalid response offset")
    if not isinstance(plan["notes"],list) or not all(isinstance(n,str) for n in plan["notes"]):raise ValueError("Driver notes required")
    return copy.deepcopy(plan)


def ready(wait,snapshot,hospital,now,*,client_requests=()):
    kind,value=next(iter(wait.items()))
    if kind=="console_bound":
        return len({r["request_id"] for r in client_requests if r["checkpoint"]==value["checkpoint"]})>=value["count"]
    if kind=="anchor":return value in hospital.scheduler.anchors
    if kind=="source_applied":
        pub=next((p for p in hospital.publications if p["id"]==value),None)
        return bool(pub and any(e["type"]=="CONTEXT_APPLIED" and e.get("event_id")==pub["event"]["event_id"] for e in snapshot["audit"]))
    if kind=="result_accepted":
        result=snapshot["latest_results"].get(value)
        return bool(result and timestamp(result["output"]["produced_time"])==timestamp(now))
    records=[r for r in snapshot["hitl_history"].values() if r["request"]["checkpoint"]==value["checkpoint"]]
    if kind=="hitl_decided":return len([r for r in records if r["status"]=="DECIDED"])>=value["count"]
    current=snapshot["open_hitl"].get(value["checkpoint"])
    return len(records)>=value["count"] and current is not None and current["status"]=="OPEN"


async def drive(plan,hospital,runtime,clock,*,write=print,poll_interval=.005,advance=None,client_requests=()):
    for tick in plan["ticks"]:
        while tick["anchor"] not in hospital.scheduler.anchors:
            snapshot=await runtime.snapshot()
            if snapshot["done"]:return
            await hospital.observe(snapshot);await asyncio.sleep(poll_interval)
        due=timestamp(hospital.scheduler.anchors[tick["anchor"]]["at"])+timedelta(seconds=tick["offset_s"])
        if due<clock.datetime():raise ValueError("Test driver cannot move its clock backwards")
        if advance:await advance(due.isoformat())
        clock.advance(due.isoformat());write("TEST_CLOCK_AT | "+clock.now())
        if "hitl_decided" in tick["wait"]:
            write("DEMO_DECISION_READY | "+tick["wait"]["hitl_decided"]["checkpoint"]+
                  " | 가상 시계가 이 시나리오의 결정 입력 시점에 도달했습니다.")
        while True:
            snapshot=await runtime.snapshot();await hospital.observe(snapshot)
            if snapshot["done"]:return
            if ready(tick["wait"],snapshot,hospital,clock.now(),client_requests=client_requests):break
            await asyncio.sleep(poll_interval)
